BOARD_TAG     = micro
BOARD_SUB     =
MONITOR_PORT  = /dev/ttyACM0
ARDUINO_SKETCHBOOK = $(CURDIR)
ARDUINO_LIBS  = Wire SPI Adafruit_GFX Adafruit_SSD1306
OBJDIR = $(CURDIR)/build
TARGET = arduino

include $(ARDMK_DIR)/Arduino.mk
